model_type: vae # vae or conv-vae 
training_params:
  max_epochs: 10
  auto_lr_find: true
  gpus: 1
model_params:
  lr: 0.001
  batch_size: 64
  hidden_size: 28
  alpha: 64
  dataset: "mnist"
  save_images: true
  save_path: "images/vae_images"
  channels: 1
  height: 28
  width: 28