training_params:
  max_epochs: 10
  auto_lr_find: false
  gpus: 1
model_params:
  model_type: conv_vae # vae or conv-vae 
  lr: 0.0005
  batch_size: 128
  hidden_size: 28
  alpha: 128
  dataset: "mnist"
  save_images: true
  save_path: "images/"
  channels: 1
  height: 28
  width: 28